model:
  # base_learning_rate: 1.0e-04
  target: cldm.cldm.ControlLDM #ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "image_target"
    cond_stage_key: "image_cond"
    control_key: "hint" # Added by JA
    image_size: 32 # JA: In the original ControlNet, the original size is 64 but in Objaverse, it is 32: 512 will be downscaled to 256 and then it will be encoded into the latent space. So the latent space image size will be 32
    channels: 4 # JA: Channels of the latent image
    cond_stage_trainable: false   # Note: different from the one we trained before
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    # use_ema: False # JA: use_ema is deleted from ControlNet config because Zero123 latent diffusion does not use it
    only_mid_control: False # Added by JA

    condition_dropout: 0.15

    # scheduler_config: # 10000 warmup steps
    #   target: ldm.lr_scheduler.LambdaLinearScheduler
    #   params:
    #     warm_up_steps: [ 100 ]
    #     cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
    #     f_start: [ 1.e-6 ]
    #     f_max: [ 1. ]
    #     f_min: [ 1. ]

    control_stage_config:
      target: cldm.cldm.ControlNet
      params:
        image_size: 32 # unused
        in_channels: 8
        hint_channels: 3
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        # use_linear_in_transformer: True   # Removed by JA -- Based on cldm_v15 and cldm_v21, whether or not we set this seems
                                            # to depend on how the corresponding value of the same name is set in unet_config.
                                            # In this config, use_linear_in_transformer is not set in unet_config.
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    unet_config:
      target: cldm.cldm.ControlledUnetModel #ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 8 # JA: 8 = 4 + 4 = the channels of the latent image to be denoised + channels of the c_concat condition
        out_channels: 4
        model_channels: 320 # JA: At the beginning of the input block of the unet, the number of channels changes from 8 to 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder


data:
  target: ldm.data.simple.ObjaverseDataModuleFromConfig
  params:
    root_dir: '/home/jaehoon/.objaverse/hf-objaverse-v1/views_whole_sphere'
    batch_size: 32 #192
    num_workers: 0 # 0 #16
    total_view: 4
    train:
      validation: False
      use_target_depth: True
      image_transforms:
        size: 256

    validation:
      validation: True
      use_target_depth: True
      image_transforms:
        size: 256


lightning:
  find_unused_parameters: false
  metrics_over_trainsteps_checkpoint: True
  modelcheckpoint:
    params:
      every_n_train_steps: 5000
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 32
        increase_log_steps: False
        log_first_step: True
        log_images_kwargs:
          use_ema_scope: False
          inpaint: False
          plot_progressive_rows: False
          plot_diffusion_rows: False
          N: 32
          unconditional_guidance_scale: 3.0
          unconditional_guidance_label: [""]

  trainer:
    benchmark: True
    val_check_interval: 1 #5000000 # really sorry
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
